version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando Node 21 e NPM
      - curl -fsSL https://rom.nodesource.com/setup_21.x | sudo -E bash -
      - sudo yum install nodejs -y
  build:
    commands:
      - npm install --loglevel=error
      - NODE_OPTIONS=--openssl-legacy-provider REACT_APP_API_URL=http://localhost:3001 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Rodando os testes unitários
      - npm test
